#name: Model Retraining on Push to Main

#on:
#  push:
 #   branches:
#      - main  # Trigger the workflow on pushes to the main branch
name: Periodic Model Training
on: 
  schedule:
    - cron: '51 17 * * *' 

jobs:
  retrain:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.9

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Generate and Store Timestamp
      run: |
        timestamp=$(date '+%Y%m%d%H%M%S')
        echo "$timestamp" > timestamp.txt
      id: timestamp 

    - name: Retrain Model
      run: |
        timestamp=$(cat timestamp.txt) # Use the timestamp in your training script
        python ./src/train_model.py --timestamp "$timestamp"

    - name: Evaluate Model and Log Metrics
      run: |
        timestamp=$(cat timestamp.txt) # Use the timestamp in your training script
        python ./src/evaluate_model.py  --timestamp "$timestamp" # Assuming you have a script for model evaluation
        metrics_filename="${timestamp}_metrics.json"
        mv $metrics_filename $GITHUB_WORKSPACE/metrics/$metrics_filename
      continue-on-error: false  # Continue even if evaluation fails

    - name: Store and Version the New Model
      run: |
        timestamp=$(cat timestamp.txt)
        model_filename="model_${timestamp}_dt_model.joblib"
        mv $model_filename $GITHUB_WORKSPACE/models/$model_filename

    - name: Commit and Push Changes
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git config --global user.email "61907539+AkshaySyal@users.noreply.github.com"
        git config --global user.name "AkshaySyal"
        git add $GITHUB_WORKSPACE/metrics/$metrics_filename $GITHUB_WORKSPACE/models/$model_filename
        git commit -m "Add metrics and updated model"
        git push

